config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :todos
  end
  root "categories#index"  # ตั้งค่าให้หน้าแรกเป็นหน้าหมวดหมู่
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :todos
  end
  

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @categories = Category.all
    end
  
    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to categories_path
      else
        render :new
      end
    end
  
    def edit
      @category = Category.find(params[:id])
    end
  
    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to categories_path
      else
        render :edit
      end
    end
  
    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      redirect_to categories_path
    end
  
    private
  
    def category_params
      params.require(:category).permit(:name)
    end
  end
  

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
      @todos = Todo.all
    end
  
    def new
      @todo = Todo.new
      @categories = Category.all
    end
  
    def create
      @todo = Todo.new(todo_params)
      if @todo.save
        redirect_to category_todos_path(@todo.category)
      else
        render :new
      end
    end
  
    def edit
      @todo = Todo.find(params[:id])
      @categories = Category.all
    end
  
    def update
      @todo = Todo.find(params[:id])
      if @todo.update(todo_params)
        redirect_to category_todos_path(@todo.category)
      else
        render :edit
      end
    end
  
    def destroy
      @todo = Todo.find(params[:id])
      @todo.destroy
      redirect_to category_todos_path(@todo.category)
    end
  
    private
  
    def todo_params
      params.require(:todo).permit(:name, :category_id, :completed)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to 'New Category', new_category_path %>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to 'Edit', edit_category_path(category) %>
      <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'View Todos', category_todos_path(category) %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Newest Todo App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= form_with(model: @todo, local: true) do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <ul>
        <% @todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', category_todos_path(@todo.category) %>

app/views/todos/index.html.erb
<h1>Todos for <%= @category.name %></h1>
<%= link_to 'New Todo', new_category_todo_path(@category) %>

<ul>
  <% @todos.each do |todo| %>
    <li>
      <%= todo.name %> - <%= todo.completed? ? 'Completed' : 'Not Completed' %>
      <%= link_to 'Edit', edit_category_todo_path(@category, todo) %>
      <%= link_to 'Delete', category_todo_path(@category, todo), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>New Todo for <%= @category.name %></h1>
<%= form_with(model: [@category, @todo], local: true) do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <ul>
        <% @todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', category_todos_path(@category) %>